#! /usr/bin/expect


#<host> <ssh user> <ssh pw>


spawn ssh [lindex $argv 1]@[lindex $argv 0] "df | grep -v Used | sort -rnsk 5 | head -1 | cut -d '%' -f1"
set timeout 2
expect {
    "yes/no" {
        send "yes\n"
        exp_continue
    }
    "*?password:" {
        send "[lindex $argv 2]\n"
        exp_continue
    }  
    "again" {
        send "root4db\n"
    }
    timeout { exit 0 }
}
interact
